package Main;

import Backend.PasswordHashing;
import DatabaseConnection.UserDAO;
import DatabaseConnection.UserInstance;
import Utilities.TextLimit;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jGreggCode
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    // Global Variables
    ImageIcon hideEye = new ImageIcon(getClass().getResource("/Images/hidepassword.png"));
    ImageIcon showEye = new ImageIcon(getClass().getResource("/Images/showpassword.png"));
    private boolean show = false;
    
    public LoginFrame() {
        // Code auto generated by netbeans
        initComponents();
        
        // Own Code
        configuration();
        
    }
    
    // Configuration
    private void configuration() {
        // Configuring the textfields
        txtAccountNo.setHint("Account Number"); // Creating account-number placeholder
        txtAccountNo.setDocument(new TextLimit(12)); // Setting the character limitation
        
        pwdPassword.setHint("Password"); // Creating password placeholder
        pwdPassword.setDocument(new TextLimit(16)); // Setting the character limitation
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblJustLogo = new javax.swing.JLabel();
        txtAccountNo = new ModifiedComponents.ModifiedTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new ModifiedComponents.ModifiedPasswordField();
        btnLogin = new ModifiedComponents.ModifiedButton();
        lblFooter = new javax.swing.JLabel();
        separatorFooter = new javax.swing.JSeparator();
        lblGetToKnow = new javax.swing.JLabel();
        lblLogintoyouraccount = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblMainBG = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblRightBackground = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GWN BANK");
        setMaximumSize(new java.awt.Dimension(1080, 639));
        setMinimumSize(new java.awt.Dimension(1080, 639));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1080, 639));
        getContentPane().setLayout(null);

        pnlLogin.setBackground(new java.awt.Color(59, 59, 59));
        pnlLogin.setMaximumSize(new java.awt.Dimension(340, 640));
        pnlLogin.setLayout(null);

        lblJustLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/JustLogo.png"))); // NOI18N
        lblJustLogo.setText("jLabel1");
        lblJustLogo.setMaximumSize(new java.awt.Dimension(120, 120));
        lblJustLogo.setMinimumSize(new java.awt.Dimension(120, 120));
        lblJustLogo.setPreferredSize(new java.awt.Dimension(120, 120));
        lblJustLogo.setVerifyInputWhenFocusTarget(false);
        pnlLogin.add(lblJustLogo);
        lblJustLogo.setBounds(110, 30, 120, 120);
        pnlLogin.add(txtAccountNo);
        txtAccountNo.setBounds(35, 230, 270, 39);

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/showpassword.png"))); // NOI18N
        lblPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showHidePassword(evt);
            }
        });
        pnlLogin.add(lblPassword);
        lblPassword.setBounds(270, 296, 24, 24);
        pnlLogin.add(pwdPassword);
        pwdPassword.setBounds(35, 290, 270, 36);

        btnLogin.setBackground(new java.awt.Color(11, 55, 234));
        btnLogin.setText("LOGIN");
        btnLogin.setFont(new java.awt.Font("Poppins", 1, 12));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(35, 370, 270, 36);

        lblFooter.setFont(new java.awt.Font("Poppins Light", 0, 10)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(255, 255, 255));
        lblFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFooter.setText("<html><center>GWN Bank is supervised by the Bangko Sentral ng Pilipinas with contact number (949) 337-3897 and email address gwnbankofficial@gmail.com <br>GWN Bank, Inc. © 2023. All Rights Reserved</html>");
        pnlLogin.add(lblFooter);
        lblFooter.setBounds(10, 540, 320, 90);
        pnlLogin.add(separatorFooter);
        separatorFooter.setBounds(35, 540, 270, 10);

        lblGetToKnow.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblGetToKnow.setForeground(new java.awt.Color(255, 255, 255));
        lblGetToKnow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGetToKnow.setText("<html><u>Know more about GWN Bank</u></html>");
        lblGetToKnow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLogin.add(lblGetToKnow);
        lblGetToKnow.setBounds(0, 450, 340, 16);

        lblLogintoyouraccount.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        lblLogintoyouraccount.setForeground(new java.awt.Color(255, 255, 255));
        lblLogintoyouraccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogintoyouraccount.setText("Login to your account");
        pnlLogin.add(lblLogintoyouraccount);
        lblLogintoyouraccount.setBounds(0, 170, 340, 30);

        lblForgotPassword.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblForgotPassword.setText("<html><u>Forgot password?</u></html>");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLogin.add(lblForgotPassword);
        lblForgotPassword.setBounds(183, 340, 120, 16);

        lblRegister.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("<html><u>Create an account?</u></html>");
        lblRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register(evt);
            }
        });
        pnlLogin.add(lblRegister);
        lblRegister.setBounds(0, 420, 340, 16);

        lblMainBG.setFont(new java.awt.Font("Karla", 0, 12)); // NOI18N
        lblMainBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gradient_img.png"))); // NOI18N
        lblMainBG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMainBG.setText("<html>BDO Unibank is supervised by the Bangko Sentral ng Pilipinas with contact number (02) 8708-7087 and email address consumeraffairs@bsp.gov.ph\n" +
            "BDO Unibank, Inc. © 2015. All Rights Reserved</html>");
        pnlLogin.add(lblMainBG);
        lblMainBG.setBounds(0, 0, 340, 640);

        getContentPane().add(pnlLogin);
        pnlLogin.setBounds(0, 0, 340, 640);

        pnlBackground.setMinimumSize(new java.awt.Dimension(739, 640));
        pnlBackground.setPreferredSize(new java.awt.Dimension(739, 640));
        pnlBackground.setLayout(null);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconExit.png"))); // NOI18N
        lblExit.setText("jLabel1");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });
        pnlBackground.add(lblExit);
        lblExit.setBounds(705, 12, 24, 24);

        lblRightBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gwnbanklogoresize.png"))); // NOI18N
        pnlBackground.add(lblRightBackground);
        lblRightBackground.setBounds(0, 0, 739, 640);

        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(340, 0, 739, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        // TODO add your handling code here:
        // JOptionPane configuration
        int option = JOptionPane.showConfirmDialog(
                null,
                "Do you wish to exit?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
        
        // If yes, then the system will exit
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_exit

    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login
        // TODO add your handling code here:
        UserDAO userDAO = new UserDAO();
        PasswordHashing passwordHashing = new PasswordHashing();
        
        String accountNumber = txtAccountNo.getText();
        String accountPassword = new String(pwdPassword.getPassword());
        
        String hashedPasswordFromDB = userDAO.getPasswordHashByUsername(accountNumber);

        if (hashedPasswordFromDB != null && passwordHashing.checkPassword(accountPassword, hashedPasswordFromDB)) {
            userDAO.getAllByUsername(accountNumber);
            this.dispose();
            new MainFrame().setVisible(true);
        } else {
            System.out.println("User not found");
        }
    }//GEN-LAST:event_login
    // Zv0SLBgVrmH9
    // 628602519917
    private void showHidePassword(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHidePassword
        // TODO add your handling code here:
        if (!show) {
            pwdPassword.setEchoChar((char) 0); // Show the password
            show = true;
            lblPassword.setIcon(showEye);
        } else {
            show = false;
            pwdPassword.setEchoChar('\u2022'); // Hide the password
            lblPassword.setIcon(hideEye);
        }
    }//GEN-LAST:event_showHidePassword

    private void register(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register
        // TODO add your handling code here:
        this.dispose();
        new RegisterFrame().setVisible(true);
    }//GEN-LAST:event_register

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Flat laf light theme (Modern looks and feel)
        //FlatLightLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); // Set FlatLaf dark theme
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ModifiedComponents.ModifiedButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblGetToKnow;
    private javax.swing.JLabel lblJustLogo;
    private javax.swing.JLabel lblLogintoyouraccount;
    private javax.swing.JLabel lblMainBG;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRightBackground;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlLogin;
    private ModifiedComponents.ModifiedPasswordField pwdPassword;
    private javax.swing.JSeparator separatorFooter;
    private ModifiedComponents.ModifiedTextField txtAccountNo;
    // End of variables declaration//GEN-END:variables
}
