package Main;

import DatabaseConnection.UserInstance;
import ModifiedComponents.RoundPanel;
import java.awt.Color;

/**
 *
 * @author jGreggCode (https://github.com/jGreggCode)
 */
public class Profile extends RoundPanel {

    /**
     * Creates new form Withdraw
     */
    public Profile() {
        initComponents();
        setVisible(false);
        //gwenchaliann@gmail.com
        UserInstance currentUser = UserInstance.getInstance();
        String fullName = currentUser.getFirstName() + " " + currentUser.getMiddleName() + " " + currentUser.getLastName(); 
        String email = currentUser.getEmail();
        String phoneNumber = currentUser.getPhoneNumber();
        String birthdate = currentUser.getBirthdate();
        System.out.println(phoneNumber);
        panelProfile.setRoundTopLeft(50);
        panelProfile.setRoundTopRight(50);
        
        lblFullName.setText(fullName);
        lblEmail.setText(email);
        lblBirthdate.setText(birthdate);
        lblPhoneNumber.setText(phoneNumber);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        panelProfile = new ModifiedComponents.RoundPanel();
        jLabel4 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setMaximumSize(new java.awt.Dimension(630, 410));
        setMinimumSize(new java.awt.Dimension(630, 410));
        setPreferredSize(new java.awt.Dimension(630, 410));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PROFILE");
        add(jLabel1);
        jLabel1.setBounds(10, 10, 610, 30);

        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        lblProfile.setText("jLabel3");
        add(lblProfile);
        lblProfile.setBounds(283, 48, 64, 64);

        panelProfile.setBackground(new java.awt.Color(255, 255, 255));
        panelProfile.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/id-card.png"))); // NOI18N
        panelProfile.add(jLabel4);
        jLabel4.setBounds(30, 70, 32, 32);

        lblFullName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblFullName.setText("John Gregg Virina Felicisimo");
        panelProfile.add(lblFullName);
        lblFullName.setBounds(80, 70, 230, 32);

        lblEmail.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblEmail.setText("felicisimojv@gmail.com");
        panelProfile.add(lblEmail);
        lblEmail.setBounds(80, 130, 230, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mail.png"))); // NOI18N
        panelProfile.add(jLabel6);
        jLabel6.setBounds(30, 130, 32, 32);

        lblBirthdate.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblBirthdate.setText("June 13, 2001");
        panelProfile.add(lblBirthdate);
        lblBirthdate.setBounds(80, 190, 230, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/birthday.png"))); // NOI18N
        panelProfile.add(jLabel8);
        jLabel8.setBounds(30, 190, 32, 32);

        lblPhoneNumber.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblPhoneNumber.setText("63+ 991 782 2877");
        panelProfile.add(lblPhoneNumber);
        lblPhoneNumber.setBounds(80, 250, 230, 32);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/call-button.png"))); // NOI18N
        panelProfile.add(jLabel10);
        jLabel10.setBounds(30, 250, 32, 32);

        add(panelProfile);
        panelProfile.setBounds(0, 80, 630, 330);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profileHeader.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblProfile;
    private ModifiedComponents.RoundPanel panelProfile;
    // End of variables declaration//GEN-END:variables
}
