package Main;

/**
 *
 * @author jovenil sacop
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modifiedTextField1 = new ModifiedComponents.ModifiedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modifiedTextField2 = new ModifiedComponents.ModifiedTextField();
        jLabel3 = new javax.swing.JLabel();
        modifiedTextField3 = new ModifiedComponents.ModifiedTextField();
        jLabel4 = new javax.swing.JLabel();
        modifiedTextField4 = new ModifiedComponents.ModifiedTextField();
        jLabel5 = new javax.swing.JLabel();
        lblHeaderCover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1150, 670));
        setMinimumSize(new java.awt.Dimension(1150, 670));
        setName("RegisterFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        modifiedTextField1.setText("modifiedTextField1");
        jPanel1.add(modifiedTextField1);
        modifiedTextField1.setBounds(60, 100, 260, 30);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Register account");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 160, 50);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 80, 120, 16);

        modifiedTextField2.setText("modifiedTextField1");
        jPanel1.add(modifiedTextField2);
        modifiedTextField2.setBounds(60, 240, 260, 30);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 220, 120, 16);

        modifiedTextField3.setText("modifiedTextField1");
        jPanel1.add(modifiedTextField3);
        modifiedTextField3.setBounds(60, 170, 260, 30);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Middle Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 150, 120, 16);

        modifiedTextField4.setText("modifiedTextField1");
        jPanel1.add(modifiedTextField4);
        modifiedTextField4.setBounds(60, 310, 260, 30);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setText("Birthdate");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 290, 120, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 223, 1150, 450);

        lblHeaderCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registerHeader.png"))); // NOI18N
        getContentPane().add(lblHeaderCover);
        lblHeaderCover.setBounds(0, 0, 1150, 230);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeaderCover;
    private ModifiedComponents.ModifiedTextField modifiedTextField1;
    private ModifiedComponents.ModifiedTextField modifiedTextField2;
    private ModifiedComponents.ModifiedTextField modifiedTextField3;
    private ModifiedComponents.ModifiedTextField modifiedTextField4;
    // End of variables declaration//GEN-END:variables
}
