/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import ModifiedComponents.RoundPanel;
import java.awt.Color;
/**
 *
 * @author jovenil sacop
 */
public class Transfer extends RoundPanel {

    /**
     * Creates new form Withdraw
     */
    public Transfer() {
        initComponents();
        setVisible(false);
        
        int frameWidth = 630;
        int frameHeight = 410;

        int componentWidth = sliderCash.getWidth();
        int componentHeight = sliderCash.getHeight();

        int centerX = (frameWidth - componentWidth) / 2;
        int centerY = (frameHeight - componentHeight) / 2;
        System.out.println("Center Pixel: (" + centerX + ", " + centerY + ")");
        
        txtAccountNumber.setCenterHint(false);
        txtAccountNumber.setHint("Account Number");
        txtCash.setText("PHP 300");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderCash = new ModifiedComponents.JSliderCustom();
        txtCash = new ModifiedComponents.ModifiedTextField();
        jLabel1 = new javax.swing.JLabel();
        modifiedButton1 = new ModifiedComponents.ModifiedButton();
        modifiedButton2 = new ModifiedComponents.ModifiedButton();
        jLabel2 = new javax.swing.JLabel();
        txtAccountNumber = new ModifiedComponents.ModifiedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(630, 410));
        setMinimumSize(new java.awt.Dimension(630, 410));
        setPreferredSize(new java.awt.Dimension(630, 410));
        setLayout(null);

        sliderCash.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                change(evt);
            }
        });
        add(sliderCash);
        sliderCash.setBounds(120, 170, 400, 40);

        txtCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCash.setEnabled(false);
        add(txtCash);
        txtCash.setBounds(190, 110, 250, 39);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMOUNT TO TRASNFER");
        add(jLabel1);
        jLabel1.setBounds(0, 10, 630, 30);

        modifiedButton1.setBackground(new Color(0xfb8a02));
        modifiedButton1.setText("CLEAR");
        modifiedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear(evt);
            }
        });
        add(modifiedButton1);
        modifiedButton1.setBounds(320, 230, 190, 30);

        modifiedButton2.setBackground(new Color(0xec3724));
        modifiedButton2.setText("CONFIRM");
        add(modifiedButton2);
        modifiedButton2.setBounds(120, 230, 190, 30);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>For hassle-free transactions, our withdrawal policy sets a minimum of PHP 300 and a maximum of PHP 50,000, ensuring both accessibility and security. The process is user-friendly, and larger transactions may require additional verification steps for your protection. Our dedicated support team is available to assist with any inquiries.</center</html>");
        add(jLabel2);
        jLabel2.setBounds(120, 280, 400, 110);

        txtAccountNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txtAccountNumber);
        txtAccountNumber.setBounds(190, 60, 250, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void change(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_change
        // TODO add your handling code here:
        int value = sliderCash.getValue();
        int roundedValue = (value / 100) * 100; // Round down to the nearest multiple of 100
        sliderCash.setValue(roundedValue); // Update the slider value

        txtCash.setText("PHP " + Integer.toString(roundedValue));
    }//GEN-LAST:event_change

    private void clear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear
        // TODO add your handling code here:
        txtCash.setText("PHP 300");
        sliderCash.setValue(300);
    }//GEN-LAST:event_clear


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private ModifiedComponents.ModifiedButton modifiedButton1;
    private ModifiedComponents.ModifiedButton modifiedButton2;
    private ModifiedComponents.JSliderCustom sliderCash;
    private ModifiedComponents.ModifiedTextField txtAccountNumber;
    private ModifiedComponents.ModifiedTextField txtCash;
    // End of variables declaration//GEN-END:variables
}
